Add content type area
Artemiris/rockart pull request #1
Opened 2020-12-09 02:25 UTC by mrstarmech

2020-12-09 08:04 UTC, vladislav-kazakov commented on console/migrations/m201203_204554_alter_table_petroglyph_add_area_id.php
> +        $this->addColumn('petroglyph', 'area_id', $this->integer());
foreign key наверное надо?

2020-12-09 08:05 UTC, vladislav-kazakov commented on console/migrations/m201208_110239_alter_table_area_language_add_column_publication.php
> +}
надо было существующую миграцию исправить, а не новую создавать

2020-12-09 08:07 UTC, vladislav-kazakov commented on console/migrations/m201201_064407_create_area_table.php
> +}
Если поле "участок" заполнено, то что будет в поле "памятник"? и возможно ли настроить ограничение целостности, чтобы исключить несоответствие памятника и участка?

2020-12-09 08:08 UTC, vladislav-kazakov commented on composer.json
> +        "php": ">=5.5",
Это для чего?

2020-12-09 08:15 UTC, vladislav-kazakov commented on frontend/controllers/AreaController.php
> +<?phpnamespace frontend\controllers;use common\models\Area;use common\models\Petroglyph;class AreaController extends \yii\web\Controller{    public function actionView($id)    {        $a
Line separator не тот. Давай пока будем считать, что во всем проекте должен быть CLRF.

2020-12-09 08:52 UTC, vladislav-kazakov commented on frontend/views/manager/archsite_create.php
> +]) ?>
проверяй, что в коммит идет. Этот файл надо было скипнуть

2020-12-12 12:39 UTC, vladislav-kazakov commented on common/models/Area.php
> +    public static function findAllOfSite($id)
Это надо было в модель Archsite: Archsite->getAreas()

2020-12-12 12:40 UTC, vladislav-kazakov commented on common/models/Petroglyph.php
> +    public static function getAllOfArea($areaId)
Это надо было в модель Area: Area->getPetroglyphs()

2020-12-12 12:42 UTC, vladislav-kazakov commented on common/models/Petroglyph.php
> +    public static function getAllOfArea($areaId)
и не забывать про         $query->where(['deleted' => null]) и $query->andWhere(['public' => 1])

2020-12-12 12:44 UTC, vladislav-kazakov reviewed
Непонятно, поисковую/фильтрационную панель ты просто убрал?

2020-12-22 05:16 UTC, vladislav-kazakov commented on common/models/Area.php
> +    public static function findAllOfSite($id)
Этот метод удалить надо теперь

2020-12-22 05:17 UTC, vladislav-kazakov commented on common/models/Petroglyph.php
> +    public static function getAllOfArea($areaId)
Этот метод удалить теперь

2020-12-22 05:17 UTC, vladislav-kazakov commented on composer.json
> +        "php": ">=5.5",
это не откатил

2020-12-22 05:22 UTC, vladislav-kazakov commented on frontend/controllers/ArchsiteController.php
> +        $areas = $archsite->areas;
тут надо было $areas = $archsite->areas; делать после проверки empty($archsite)

2020-12-22 05:27 UTC, vladislav-kazakov commented on frontend/controllers/ManagerController.php
> +            \Yii::$app->session->setFlash('error', "Не удалось удалить памятник<br>Проверьте, что на памятнике не осталось участков");
русский текст сделать через словарь

2020-12-22 05:29 UTC, vladislav-kazakov commented on frontend/controllers/ManagerController.php
> +            \Yii::$app->session->setFlash('error', "Не удалось удалить памятник<br>Проверьте, что на памятнике не осталось участков");
и у нас может памятник не удаляться, потому что в нем плоскости есть. Надо поправить сообщение

2020-12-22 05:34 UTC, vladislav-kazakov commented on frontend/controllers/PetroglyphController.php
> +            } else if ($petroglyph->archsite->lat && $petroglyph->archsite->lng){
Старайся писать единообразно. Тут почему-то для area ты инициализировал отдельную переменную $area, а для archsite - нет, и обращаешься к нему $petroglyph->archsite.

2020-12-22 05:35 UTC, vladislav-kazakov commented on frontend/views/archsite/view.php
>  JS;
Мы обсуждали, что фильтрационную панель надо вернуть для памятника, если в нем есть плоскости.

2020-12-22 05:37 UTC, vladislav-kazakov commented on frontend/views/area/view.php
> +<?php/* @var $this yii\web\View *//* @var $archsite Archsite *//* @var $area Area *//* @var $petroglyphs Array */use yii\helpers\Html;use yii\helpers\Url;use common\models\Archsite;use comm
сделай CLRF, не могу код ревью делать

2020-12-22 05:52 UTC, vladislav-kazakov commented on frontend/views/layouts/_filter_bar.php
> +use yii\helpers\ArrayHelper;
что-то не вижу, где тут ArrayHelper используется.

2020-12-22 06:10 UTC, vladislav-kazakov requested changes
см. комменты

2020-12-24 11:54 UTC, mrstarmech commented on frontend/views/layouts/_filter_bar.php
> +use yii\helpers\ArrayHelper;
Убрал

2020-12-24 14:57 UTC, vladislav-kazakov commented on frontend/controllers/ArchsiteController.php
> -            'filter' => $filter
Разве тут не надо было вернуть тоже фильтрацию?

2020-12-27 15:48 UTC, vladislav-kazakov approved these changes

2020-12-27 15:56 UTC, merged